In [204]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [205]:
Path = 'drive/My Drive/Epson iPrint'

Import Library

In [206]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [207]:
df = pd.read_csv (Path+'/Womens_Clothing_E-Commerce_Reviews[1].csv')

In [208]:
df = pd.read_csv('/content/drive/MyDrive/Epson iPrint/Womens_Clothing_E-Commerce_Reviews[1].csv')

In [209]:
df.head()

Unnamed: 0  Clothing ID  Age                    Title  \
0           0          767   33                      NaN   
1           1         1080   34                      NaN   
2           2         1077   60  Some major design flaws   
3           3         1049   50         My favorite buy!   
4           4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [210]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Unnamed: 0               23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [211]:
df.shape

(23486, 11)

Missing Values

In [212]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [213]:
df[df['Review Text']==""]=np.NaN

In [214]:
df['Review Text'].fillna("No Review", inplace=True)

In [215]:
df.isna().sum()

Unnamed: 0                    0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [216]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

In [217]:
df.columns

Index(['Unnamed: 0', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [218]:
x=df['Review Text']

In [219]:
y=df['Rating']

In [220]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [221]:
from sklearn.model_selection import train_test_split

In [222]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.7,stratify=y,random_state=162529)

In [223]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((7045,), (16441,), (7045,), (16441,))

In [224]:
from sklearn.feature_extraction.text import CountVectorizer

In [225]:
cv = CountVectorizer(lowercase = True, analyzer='word',ngram_range=(2, 3), stop_words = 'english',max_features=5000)

In [226]:
x_train=cv.fit_transform(x_train)

In [227]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'yellow just',
       'yoga pants'], dtype=object)

In [228]:
x_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [229]:
x_test=cv.fit_transform(x_test)

In [230]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years old', 'yellow color',
       'yoga pants'], dtype=object)

In [231]:
x_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

Get Model Train

In [232]:
from sklearn.naive_bayes import MultinomialNB

In [233]:
model = MultinomialNB()

In [234]:
model.fit(x_train, y_train)

MultinomialNB()

Get Model Prediction

In [235]:
y_pred = model.predict(x_test)

In [236]:
y_pred.shape

(16441,)

In [237]:
y_pred

array([4., 5., 4., ..., 4., 5., 5.])

Get Probability of Each Predicted Class

In [238]:
model.predict_proba(x_test)

array([[0.36463703, 0.05682084, 0.15516574, 0.37286995, 0.05050644],
       [0.04030735, 0.01287008, 0.05392844, 0.22036209, 0.67253203],
       [0.06336521, 0.15552512, 0.01049034, 0.71887725, 0.05174208],
       ...,
       [0.09712025, 0.00430869, 0.29587415, 0.58035046, 0.02234645],
       [0.20597243, 0.16305784, 0.07434472, 0.07718999, 0.47943503],
       [0.03591199, 0.06657204, 0.12221434, 0.21618169, 0.55911994]])

Get Model Evaluation

In [239]:
from sklearn.metrics import confusion_matrix, classification_report

In [240]:
print(confusion_matrix(y_test, y_pred))

[[  37   69   83  100  300]
 [  99  143  190  180  484]
 [ 208  264  340  376  822]
 [ 389  364  528  714 1559]
 [1001  886 1238 1685 4382]]


In [241]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.06      0.03       589
         2.0       0.08      0.13      0.10      1096
         3.0       0.14      0.17      0.15      2010
         4.0       0.23      0.20      0.22      3554
         5.0       0.58      0.48      0.52      9192

    accuracy                           0.34     16441
   macro avg       0.21      0.21      0.21     16441
weighted avg       0.40      0.34      0.37     16441



Recategories Ratings as Poor (0) and Good (1)

In [242]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

Re-Rating as 1,2,3 as 0 and 4,5 as 1

In [243]:
df.replace({'Rating':{ 1:0, 2:0, 3:0, 4:1, 5:1}}, inplace=True)

In [244]:
y = df['Rating']

In [245]:
x = df['Review Text']

Get Model Re-Train

In [246]:
from sklearn.naive_bayes import MultinomialNB

In [247]:
model = MultinomialNB()

In [248]:
model.fit(x_train,y_train)

MultinomialNB()

Get Model Prediction

In [249]:
y_pred = model.predict(x_test)

In [250]:
y_pred.shape

(16441,)

In [251]:
y_pred

array([4., 5., 4., ..., 4., 5., 5.])

Get Model Evaluation

In [252]:
from sklearn.metrics import confusion_matrix, classification_report

In [253]:
print(confusion_matrix(y_test, y_pred))

[[  37   69   83  100  300]
 [  99  143  190  180  484]
 [ 208  264  340  376  822]
 [ 389  364  528  714 1559]
 [1001  886 1238 1685 4382]]


In [254]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.06      0.03       589
         2.0       0.08      0.13      0.10      1096
         3.0       0.14      0.17      0.15      2010
         4.0       0.23      0.20      0.22      3554
         5.0       0.58      0.48      0.52      9192

    accuracy                           0.34     16441
   macro avg       0.21      0.21      0.21     16441
weighted avg       0.40      0.34      0.37     16441

